version: "3"
services:
    db:
        container_name: olist_mysql_db
        image: mysql:5.7
        ports:
            - "32002:3306"
        environment:
            MYSQL_ROOT_PASSWORD: rootpwd2
            MYSQL_DATABASE: olist_ecommerce
        volumes:
            - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
